name: AzureTest
on: 
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - name: Login to Azure
      uses: azure/login@v2
      with: 
        creds: ${{ secrets.AZURE_CRED }} 
